### ISSUE TITLE
Running your code in a "Google Colab"

### ISSUE THREAD

**Issue by steinhaug** [CoffeeVampir3/audiocraft-webui#4]
Im trying to run your code so that I get a URL typical of those share=True, could you add the needed code so I get that extra URL?

Thanks in advance.

**Comment by CoffeeVampir3** [comment]
The main repository isin't a gradio project, but I do have an experimental one here:
[Gradio Version](https://github.com/CoffeeVampir3/audiocraft-webui/tree/gradio-version)
