### ISSUE TITLE
Could not save file due to length issue

### ISSUE THREAD

**Issue by zslittlehelper** [CoffeeVampir3/audiocraft-webui#5]
(Running on WSL)
I experimented with a long prompt and the resulting file could not be saved.
Automatic truncation of the filename (before saving) would be appreciated.

**Comment by CoffeeVampir3** [comment]
I have no windows machine to test with, hopefully this is fixed with this:
<https://github.com/CoffeeVampir3/audiocraft-webui/commit/abc2ad597eda5c1310083ad0f67bc31f1e7c5046>

Pull the latest and let me know if this is still an issue

**Comment by zslittlehelper** [comment]
This does indeed solve it! Many thanks.
