### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by DanG31538** [CoffeeVampir3/audiocraft-webui#8]
127.0.0.1 - - [23/Jun/2023 21:56:20] "GET /static/audio/audio_file_name.wav HTTP/1.1" 404 -

I get something like this and I am wondering if it has something to do with configuring the server to serve static files?
Running it from WSL. UI loads fine. When submitting, the audio file is never generated in the static sub-directory and then I get the above error

**Comment by CoffeeVampir3** [comment]
This is odd, do you get any errors in the web console or in the python outputs?

at the beginning of the webui.py file you can delete the lines:
```python
logging.getLogger().setLevel(logging.ERROR)
logging.getLogger('engineio').setLevel(logging.ERROR)
logging.getLogger('socketio').setLevel(logging.ERROR)
```

this will cause basically everything to be logged and might reveal some sort of error.
