### ISSUE TITLE
"MusicGen pretrained model relying on deprecated checkpoint mapping."

### ISSUE THREAD

**Issue by thelebaron** [CoffeeVampir3/audiocraft-webui#9]
Full error: 
Loading model melody
C:\Users\adminuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\audiocraft\models\musicgen.py:112: UserWarning: MusicGen pretrained model relying on deprecated checkpoint mapping. Please use full pre-trained id instead: facebook/musicgen-melody
  warnings.warn(

I'm getting this error after a model is downloaded. Somewhat unsure how to proceed from here, is there an older version of audiocraft that works that i should install?

**Comment by CoffeeVampir3** [comment]
It looks like their was a huge amount of changes a few days ago, i'm looking into a fix

**Comment by CoffeeVampir3** [comment]
Should be fixed now <https://github.com/CoffeeVampir3/audiocraft-webui/commit/11fb64cd36d9afe3675d9105a3df1661be5537d9>
